<?php

namespace DDWPTweaks\Tweaks;

return [
    'id'    => 'ddwpt_acf_site_options',
    'label' => 'ACF Site Options',
    'tab'   => 'general',

    'settings' => [
        [
            'id'          => 'enabled',
            'type'        => 'checkbox',
            'label'       => 'Enable tweak',
            'description' => 'Register the Site Options ACF field group and options page (Branding & Extras).',
        ],
    ],

    'callback' => function ($settings) {
        if (empty($settings['enabled'])) {
            return;
        }

        // The tweak callback fires at init priority 10; ACF initialises at
        // init priority 10 but registers earlier (alphabetically), so both
        // acf/init and acf/include_fields have already fired by the time we
        // run. Call the ACF functions directly — they work fine here.

        if (!function_exists('acf_add_options_page')) {
            return;
        }

        acf_add_options_page(array(
                'page_title' => 'Branding &amp; Extras',
                'menu_slug'  => 'site-options',
                'position'   => '',
                'redirect'   => false,
                'menu_icon'  => array(
                    'type'  => 'url',
                    'value' => 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjUiIHZpZXdCb3g9IjAgMCAyNCAyNSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYuMDAxIDBDMjAuNDE4NyAwLjAwMDI1OTMzOSAyMy45OTk5IDMuNTkwMTggMjQgOC4wMTg1NVYxNi4wMzkxQzIzLjk5OTkgMjAuNDY3NCAyMC40MTg3IDI0LjA1NzQgMTYuMDAxIDI0LjA1NzZINy45OTkwMkMzLjU4MTMxIDI0LjA1NzQgMC4wMDAxMTQxNDMgMjAuNDY3NCAwIDE2LjAzOTFWOC4wMTg1NUM2LjQ3ODI2ZS0wNSAzLjU5MDE4IDMuNTgxMjggMC4wMDAyNTgzMSA3Ljk5OTAyIDBIMTYuMDAxWk0xMy44Nzk5IDkuMTk4MjRWMTIuMjYzN0gxMC44MTkzVjkuMTk4MjRIMTMuODc5OVpNNC43MDYwNSA5LjE5ODI0SDcuNzU3ODFWMTguMzkzNkgxMC44MTkzVjE1LjMyODFIMTYuOTQxNFY2LjEzMjgxSDEwLjgxOTNWOS4xOTgyNEg3Ljc2NzU4VjYuMTMyODFINC43MDYwNVY5LjE5ODI0WiIgZmlsbD0id2hpdGUiLz48L3N2Zz4=',
                ),
                'icon_url'   => 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjUiIHZpZXdCb3g9IjAgMCAyNCAyNSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYuMDAxIDBDMjAuNDE4NyAwLjAwMDI1OTMzOSAyMy45OTk5IDMuNTkwMTggMjQgOC4wMTg1NVYxNi4wMzkxQzIzLjk5OTkgMjAuNDY3NCAyMC40MTg3IDI0LjA1NzQgMTYuMDAxIDI0LjA1NzZINy45OTkwMkMzLjU4MTMxIDI0LjA1NzQgMC4wMDAxMTQxNDMgMjAuNDY3NCAwIDE2LjAzOTFWOC4wMTg1NUM2LjQ3ODI2ZS0wNSAzLjU5MDE4IDMuNTgxMjggMC4wMDAyNTgzMSA3Ljk5OTAyIDBIMTYuMDAxWk0xMy44Nzk5IDkuMTk4MjRWMTIuMjYzN0gxMC44MTkzVjkuMTk4MjRIMTMuODc5OVpNNC43MDYwNSA5LjE5ODI0SDcuNzU3ODFWMTguMzkzNkgxMC44MTkzVjE1LjMyODFIMTYuOTQxNFY2LjEzMjgxSDEwLjgxOTNWOS4xOTgyNEg3Ljc2NzU4VjYuMTMyODFINC43MDYwNVY5LjE5ODI0WiIgZmlsbD0id2hpdGUiLz48L3N2Zz4=',
            ));

        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        acf_add_local_field_group(array(
                'key'   => 'group_66d540426b8e3',
                'title' => 'Site Options',
                'fields' => array(
                    array(
                        'key'               => 'field_66d544438d7a3',
                        'label'             => 'Branding',
                        'name'              => '',
                        'aria-label'        => '',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'placement'         => 'top',
                        'endpoint'          => 0,
                        'selected'          => 0,
                    ),
                    array(
                        'key'               => 'field_66d544538d7a4',
                        'label'             => 'Brand Logo',
                        'name'              => 'so_brand_logo',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'allow_in_bindings' => 0,
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_66d5404204526',
                        'label'             => 'Social Settings',
                        'name'              => '',
                        'aria-label'        => '',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'placement'         => 'top',
                        'endpoint'          => 0,
                        'selected'          => 0,
                    ),
                    array(
                        'key'               => 'field_66d5416f0452a',
                        'label'             => 'Facebook URL',
                        'name'              => 'so_facebook_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d541930452b',
                        'label'             => 'Instagram URL',
                        'name'              => 'so_instagram_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d541a50452c',
                        'label'             => 'X (Formerly Twitter) URL',
                        'name'              => 'so_twitter_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d541bd0452d',
                        'label'             => 'LinkedIn URL',
                        'name'              => 'so_linkedin_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d541cd0452e',
                        'label'             => 'YouTube URL',
                        'name'              => 'so_youtube_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5425404531',
                        'label'             => 'TikTok URL',
                        'name'              => 'so_tiktok_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5427304532',
                        'label'             => 'Pinterest URL',
                        'name'              => 'so_pinterest_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5421a0452f',
                        'label'             => 'WhatsApp URL',
                        'name'              => 'so_whatsapp_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5422904530',
                        'label'             => 'Reddit URL',
                        'name'              => 'so_reddit_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5428804533',
                        'label'             => 'LinkTree URL',
                        'name'              => 'so_linktree_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5429604534',
                        'label'             => 'Vimeo URL',
                        'name'              => 'so_vimeo_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d542a504535',
                        'label'             => 'Google Business Profile URL',
                        'name'              => 'so_gmb_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                    ),
                    array(
                        'key'               => 'field_66d5408904527',
                        'label'             => 'Contact Settings',
                        'name'              => '',
                        'aria-label'        => '',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'placement'         => 'top',
                        'endpoint'          => 0,
                        'selected'          => 0,
                    ),
                    array(
                        'key'               => 'field_66d542c804536',
                        'label'             => 'Phone Number',
                        'name'              => 'so_phone_number',
                        'aria-label'        => '',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'return_format'     => 'array',
                        'allow_in_bindings' => 0,
                    ),
                    array(
                        'key'               => 'field_66d5438171ec1',
                        'label'             => 'Email Address',
                        'name'              => 'so_email_address',
                        'aria-label'        => '',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'return_format'     => 'array',
                        'allow_in_bindings' => 0,
                    ),
                    array(
                        'key'               => 'field_66d540a404528',
                        'label'             => 'Primary Address',
                        'name'              => 'so_primary_address',
                        'aria-label'        => '',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'return_format'     => 'array',
                        'allow_in_bindings' => 0,
                    ),
                    array(
                        'key'               => 'field_66d5414704529',
                        'label'             => 'Operating Hours',
                        'name'              => 'so_operating_hours',
                        'aria-label'        => '',
                        'type'              => 'repeater',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'layout'            => 'table',
                        'pagination'        => 0,
                        'min'               => 0,
                        'max'               => 0,
                        'collapsed'         => '',
                        'button_label'      => 'Add Row',
                        'rows_per_page'     => 20,
                        'sub_fields'        => array(
                            array(
                                'key'               => 'field_68ef2939bc4f8',
                                'label'             => 'Day',
                                'name'              => 'day',
                                'aria-label'        => '',
                                'type'              => 'text',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                                'default_value'     => '',
                                'maxlength'         => '',
                                'allow_in_bindings' => 0,
                                'placeholder'       => '',
                                'prepend'           => '',
                                'append'            => '',
                                'parent_repeater'   => 'field_66d5414704529',
                            ),
                            array(
                                'key'               => 'field_68ef2941bc4f9',
                                'label'             => 'Open Time',
                                'name'              => 'open_time',
                                'aria-label'        => '',
                                'type'              => 'time_picker',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                                'display_format'    => 'g:i a',
                                'return_format'     => 'g:i a',
                                'allow_in_bindings' => 0,
                                'parent_repeater'   => 'field_66d5414704529',
                            ),
                            array(
                                'key'               => 'field_68ef294dbc4fa',
                                'label'             => 'End Time',
                                'name'              => 'end_time',
                                'aria-label'        => '',
                                'type'              => 'time_picker',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                                'display_format'    => 'g:i a',
                                'return_format'     => 'g:i a',
                                'allow_in_bindings' => 0,
                                'parent_repeater'   => 'field_66d5414704529',
                            ),
                            array(
                                'key'               => 'field_68ef2959bc4fb',
                                'label'             => 'Override Text',
                                'name'              => 'override_text',
                                'aria-label'        => '',
                                'type'              => 'text',
                                'instructions'      => 'Overrides the time fields, for instance when you want to say "Closed" or "By Appointment"',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                                'default_value'     => '',
                                'maxlength'         => '',
                                'allow_in_bindings' => 0,
                                'placeholder'       => '',
                                'prepend'           => '',
                                'append'            => '',
                                'parent_repeater'   => 'field_66d5414704529',
                            ),
                        ),
                    ),
                    array(
                        'key'               => 'field_66d5433b71ebd',
                        'label'             => 'Map Embed',
                        'name'              => '',
                        'aria-label'        => '',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'placement'         => 'top',
                        'endpoint'          => 0,
                        'selected'          => 0,
                    ),
                    array(
                        'key'               => 'field_66d5434b71ebe',
                        'label'             => 'Latitude',
                        'name'              => 'so_map_latitude',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_66d5435271ebf',
                        'label'             => 'Longitude',
                        'name'              => 'so_map_longitude',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'allow_in_bindings' => 0,
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_66d5436871ec0',
                        'label'             => 'Map Icon',
                        'name'              => 'so_map_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'allow_in_bindings' => 0,
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_66d543be96d8f',
                        'label'             => 'Announcement Bar',
                        'name'              => '',
                        'aria-label'        => '',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'placement'         => 'top',
                        'endpoint'          => 0,
                        'selected'          => 0,
                    ),
                    array(
                        'key'               => 'field_66d543cd96d90',
                        'label'             => 'Enabled',
                        'name'              => 'so_announcement_enabled',
                        'aria-label'        => '',
                        'type'              => 'true_false',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'message'           => '',
                        'default_value'     => 0,
                        'allow_in_bindings' => 0,
                        'ui_on_text'        => '',
                        'ui_off_text'       => '',
                        'ui'                => 1,
                    ),
                    array(
                        'key'               => 'field_66d543f196d91',
                        'label'             => 'Announcement Bar Content',
                        'name'              => 'so_announcement_content',
                        'aria-label'        => '',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field'    => 'field_66d543cd96d90',
                                    'operator' => '==',
                                    'value'    => '1',
                                ),
                            ),
                        ),
                        'wrapper'           => array('width' => '', 'class' => '', 'id' => ''),
                        'default_value'     => '',
                        'allow_in_bindings' => 0,
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param'    => 'options_page',
                            'operator' => '==',
                            'value'    => 'site-options',
                        ),
                    ),
                ),
                'menu_order'          => 0,
                'position'            => 'normal',
                'style'               => 'default',
                'label_placement'     => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen'      => '',
                'active'              => true,
                'description'         => '',
                'show_in_rest'        => 0,
                'display_title'       => 'Configure Site Options',
                'allow_ai_access'     => false,
                'ai_description'      => '',
            ));
    },
];
